// Mock data for the application
export const clubs = [
  {
    id: 1,
    name: "Code Champions",
    category: "TECH",
    description:
      "Câu lạc bộ lập trình hàng đầu của trường. Tham gia các cuộc thi, workshop và xây dựng các dự án công nghệ.",
    members: 15,
    events: 8,
    successRate: "95%",
    image: "/coding-programming-tech.jpg",
  },
  {
    id: 2,
    name: "AI Innovation Club",
    category: "TECH",
    description: "Khám phá thế giới trí tuệ nhân tạo và machine learning. Tập trung vào nghiên cứu và ứng dụng AI.",
    members: 12,
    events: 5,
    successRate: "92%",
    image: "/artificial-intelligence-ai-robot.jpg",
  },
  {
    id: 3,
    name: "Vovinam Club",
    category: "SPORT",
    description:
      "Câu lạc bộ võ thuật truyền thống Việt Nam. Tham gia giải đấu, rèn luyện sức khỏe và xây dựng tinh thần đồng đội.",
    members: 20,
    events: 3,
    successRate: "98%",
    image: "/martial-arts-vovinam-sport.jpg",
  },
]

export const events = [
  {
    id: 1,
    title: "RESEARCH CONNECT 2025",
    description:
      "Những giây phút cùng thăng và hỗi hợp sáng sủa ra tiến đầu trường học thuật, sân chơi nghiên cứu khoa học tầm nhất mành dành cho sinh viên Trường F.",
    date: "2025-01-28",
    time: "19:30",
    category: "ACADEMIC",
    status: "upcoming",
    participants: 0,
    maxParticipants: 100,
    image: "/research-conference-academic.jpg",
    location: "Phòng hội thảo B201",
    organizer: "CLB Nghiên cứu khoa học",
    tags: ["Nghiên cứu", "Khoa học", "Học thuật"],
  },
  {
    id: 2,
    title: "Hackathon 2025",
    description:
      "Thử thách bản thân với 48 giờ coding marathon cùng các developer hàng đầu. Giải thưởng hấp dẫn và cơ hội networking với các chuyên gia trong ngành.",
    date: "2025-02-15",
    time: "09:00",
    category: "TECH",
    status: "upcoming",
    participants: 45,
    maxParticipants: 100,
    image: "/hackathon-coding-programming.jpg",
    location: "Lab máy tính A101",
    organizer: "CLB Lập trình",
    tags: ["Lập trình", "Hackathon", "Công nghệ"],
  },
  {
    id: 3,
    title: "Cuộc thi lập trình Hackathon",
    description:
      "Thử thách bản thân với 48 giờ coding marathon cùng các developer hàng đầu. Giải thưởng hấp dẫn và cơ hội networking với các chuyên gia trong ngành.",
    date: "2025-01-15",
    time: "08:00",
    category: "TECH",
    status: "registered",
    participants: 28,
    maxParticipants: 30,
    image: "/coding-programming-tech.jpg",
    location: "CLB Lập trình",
    organizer: "CLB Lập trình",
    tags: ["Lập trình", "Thi đấu"],
  },
  {
    id: 4,
    title: "Giải bóng đá sinh viên",
    description: "Tham gia bóng đá 11 người giữa các khoa, các câu lạc bộ. Cơ hội thể hiện tài năng và tình đoàn kết.",
    date: "2025-01-20",
    time: "15:00",
    category: "SPORT",
    status: "registered",
    participants: 22,
    maxParticipants: 22,
    image: "/martial-arts-vovinam-sport.jpg",
    location: "CLB Thể thao",
    organizer: "CLB Thể thao",
    tags: ["Thể thao", "Bóng đá"],
  },
  {
    id: 5,
    title: "Đêm nhạc acoustic",
    description:
      "Một đêm nhạc đầy cảm xúc với những giai điệu acoustic nhẹ nhàng. Không gian ấm cúng để gần gũi sau những ngày học tập căng thẳng.",
    date: "2025-01-25",
    time: "19:00",
    category: "ART",
    status: "registered",
    participants: 156,
    maxParticipants: 200,
    image: "/placeholder.svg?key=music",
    location: "CLB Âm nhạc",
    organizer: "CLB Âm nhạc",
    tags: ["Âm nhạc", "Acoustic"],
  },
  {
    id: 6,
    title: "Workshop kỹ năng mềm",
    description:
      "Nâng cao kỹ năng giao tiếp, làm việc nhóm và thuyết trình. Được hướng dẫn bởi các chuyên gia và leader có kinh nghiệm.",
    date: "2025-02-01",
    time: "14:00",
    category: "ACADEMIC",
    status: "registered",
    participants: 45,
    maxParticipants: 50,
    image: "/placeholder.svg?key=workshop",
    location: "CLB Học thuật",
    organizer: "CLB Học thuật",
    tags: ["Kỹ năng mềm", "Workshop"],
  },
  {
    id: 7,
    title: "Cuộc thi AI và Machine Learning",
    description:
      "Thử sức với các dự án AI thực tế. Tổ chức computer vision đến natural language processing. Cơ hội học hỏi từ các mentor công nghệ.",
    date: "2025-02-10",
    time: "10:00",
    category: "TECH",
    status: "registered",
    participants: 32,
    maxParticipants: 40,
    image: "/artificial-intelligence-ai-robot.jpg",
    location: "CLB AI Research",
    organizer: "CLB AI Research",
    tags: ["AI", "Machine Learning"],
  },
  {
    id: 8,
    title: "Triển lãm nghệ thuật sinh viên",
    description:
      "Trưng bày các tác phẩm nghệ thuật của sinh viên. Từ hội họa, nhiếp ảnh đến điêu khắc. Không gian sáng tạo và cảm hứng.",
    date: "2025-02-05",
    time: "16:00",
    category: "ART",
    status: "registered",
    participants: 89,
    maxParticipants: 100,
    image: "/placeholder.svg?key=art",
    location: "CLB Mỹ thuật",
    organizer: "CLB Mỹ thuật",
    tags: ["Nghệ thuật", "Triển lãm"],
  },
]

export const testimonials = [
  {
    id: 1,
    name: "Xavier",
    avatar: "/male-student-avatar.png",
    rating: 5,
    comment:
      "Thanks to this project we discovered and realized our brand was so much more than what we thought. We are really happy about the results.",
  },
  {
    id: 2,
    name: "Mr. Thiện",
    avatar: "/teacher-avatar-male.jpg",
    rating: 5,
    comment:
      "Not only the project inspired us about our brand, but the actual results we were able to accomplish were amazing.",
  },
  {
    id: 3,
    name: "Donald Trump",
    avatar: "/student-avatar.png",
    rating: 5,
    comment:
      "This boy is really good and I am excited about this work. I think it was the best I have seen in my years.",
  },
]

export const categories = [
  { id: "all", label: "Tất cả", color: "bg-red-500" },
  { id: "TECH", label: "Công nghệ", color: "bg-blue-500" },
  { id: "SPORT", label: "Thể thao", color: "bg-green-500" },
  { id: "ART", label: "Nghệ thuật", color: "bg-purple-500" },
  { id: "ACADEMIC", label: "Học thuật", color: "bg-orange-500" },
  { id: "CULTURE", label: "Văn hóa", color: "bg-teal-500" },
]
